<?php
// +----------------------------------------------------------------------
// | ThinkCMF [ WE CAN DO IT MORE SIMPLE ]
// +----------------------------------------------------------------------
// | Copyright (c) 2013-2018 http://www.thinkcmf.com All rights reserved.
// +----------------------------------------------------------------------
// | Licensed ( http://www.apache.org/licenses/LICENSE-2.0 )
// +----------------------------------------------------------------------
// | Author: 老猫 <thinkcmf@126.com>
// +----------------------------------------------------------------------
namespace app\portal\controller;

use cmf\controller\HomeBaseController;
use app\order\model\OrderBookModel;
use app\goods\model\GoodsCarStyleModel;
use app\goods\model\GoodsCarSeriesModel;
use think\exception\ErrorException;


class ChannelController extends HomeBaseController
{
    private $book_car_manger_email = '7124046@qq.com';//'2915295429@qq.com';

    public function index()
    {
        return $this->fetch();
    }
    public function chuanqi(){

        //$series = new GoodsCarSeriesModel();
        $brand_id = 5;
        $brand_name = '广汽传祺';
        //$series->getCarSeriesByBrandId($brand_id);
        $chuanqi = [
            [
                'id'=>7,
                'name'=>'传祺GS4',
                'price'=>'7.08',
                'img'=>'gs4.jpg',
            ],
            [
                'id'=>8,
                'name'=>'传祺GS8',
                'price'=>'15.38',
                'img'=>'gs8.jpg',
            ],
            [
                'id'=>9,
                'name'=>'传祺GS3',
                'price'=>'6.78',
                'img'=>'gs3.jpg',
            ],
            [
                'id'=>6,
                'name'=>'传祺GS7',
                'price'=>'13.98',
                'img'=>'gs7.jpg',
            ],
            [
                'id'=>10,
                'name'=>'传祺GA6',
                'price'=>'7.78',
                'img'=>'ga6.jpg',
            ],
            [
                'id'=>11,
                'name'=>'传祺GA8',
                'price'=>'12.98',
                'img'=>'ga8.jpg',
            ],
            [
                'id'=>4,
                'name'=>'传祺GA4',
                'price'=>'6.78',
                'img'=>'ga4.jpg',
            ],
            [
                'id'=>5,
                'name'=>'传祺GM8',
                'price'=>'17.68',
                'img'=>'gm8.jpg',
            ],
        ];
        $this->assign('chuanqi',$chuanqi);
        $this->assign('brand_id',$brand_id);
        $this->assign('brand_name',$brand_name);
        return $this->fetch();
    }

    public function weyP8(){
        if(cmf_is_mobile()){
            return $this->fetch('mobile_wey');
        }else{
            $brand_id = 3;//wey
            $goodsCarSeriesModel = new  GoodsCarSeriesModel();
            $weyp8_styles =  $goodsCarSeriesModel->getCarSeriesByBrandId($brand_id);
            $this->assign('weyp8Styles',$weyp8_styles);
            $car_configs = $this->p8ConfigData();
            $this->assign('carConfigs',$car_configs);

            return $this->fetch('wey_p8');
        }
    }
    public function ajaxWeyTestDrive(){
        return $this->fetch('test_drive');
    }
    /**
     * 获取车型表单
     * @return mixed
     */
    public function ajaxWeyForm(){
        $series_id = I('series_id');
        $goodsCarStyleModel = new  GoodsCarStyleModel();
        $wey_styles = $goodsCarStyleModel->getCarStyleDataBySeriesId($series_id);
        $this->assign('weyCarStyles',$wey_styles);
        $this->assign('series_id',$series_id);
        return $this->fetch('ajax_wey_form');
    }

    /**
     * 预约试驾表单提交
     *
     */
    public function ajaxSubmitBookCar(){
        $series_id = I('series_id');
        //$style_id = I('style_id');
        $customer_name = I('customer_name');
        $mobile = I('mobile');
       if(empty($series_id)){
           $this->result('',0,'请选择车型');
       }
        /*if(empty($style_id)){
            $this->result('',0,'请选择车型');
        }*/
        if(empty($customer_name)){
            $this->result('',0,'请填写姓名');
        }
        if(empty($mobile)){
            $this->result('',0,'请填写电话号码');
        }
        if(strlen($mobile) !== 11|| !preg_match('/^(13[0-9]|15[0-9]|18[0-9])\d{8}$/',$mobile)){
            $this->result('',0,'请输入正确的手机号码格式');
        }

        $wh = [];
        //$wh['car_style_id'] = $style_id;
        $wh['series_id'] = $series_id;
        $wh['book_telephone'] = $mobile;
        $wh['dealers_id'] = 0;
        $wh['delete_time'] = 0;
        $orderBookModel = new OrderBookModel();
        $count = $orderBookModel->where($wh)->count();
        if($count>0){
            $this->result('',-1,'您已经预约');
        }
        $data['name'] = $customer_name;
        $data['area_id'] = 4403; // 区级id 深圳
        $data['sex'] = 0; // 性别id
        $data['car_style_id'] = 0; // 车型id
        $data['book_time'] = time(); // 发布时间
        $data['book_to_time'] = 0; // 预约到店时间
        $data['book_telephone'] = $mobile; // 电话
        $data['series_id'] = $series_id; // 车系

        try{
            $id = $orderBookModel->addOrderBookData($data);
            if($id){
                // 给运维人员发邮件通知
                $email_config['to'] = $this->book_car_manger_email;
                $email_config['subject'] = '预约试驾';
                $email_tpl = '<table border="0" cellspacing="0" cellpadding="0" width="40%%" align="center">
            <tr>
                <td width="17%%" align="left" height="36" style="font-size: 14px;border-top: 1px solid  #cdd1dc;
    border-left: 1px solid  #cdd1dc; padding-left: 5px;">客&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;户:</td>
                <td width="83%%" align="left" height="36" style="font-size: 14px;color: #40485B;border-top: 1px solid  #cdd1dc;
    border-right: 1px solid  #cdd1dc;">%s</td>
            </tr>
            <tr>
                <td colspan="2" align="left" height="36" style="padding-left:30px;font-size: 14px;border-right: 1px solid #cdd1dc;border-left: 1px solid  #cdd1dc;color:#40485B;">于 %s 预约试驾！</td>
            </tr>
            <tr>
                <td width="17%%" style="font-size: 14px;
    border-left: 1px solid  #cdd1dc; padding-left: 5px;">预约车型:</td>
                <td width="83%%" align="left" height="36" style="font-size: 14px; color: #40485B;
    border-right: 1px solid  #cdd1dc;" >%s</td>
            </tr>
            <tr>
                <td width="17%%" style="font-size: 14px;border-bottom: 1px solid  #cdd1dc;
    border-left: 1px solid  #cdd1dc; padding-left: 5px;">联系电话:</td>
                <td width="83%%" align="left" height="36" style="font-size: 14px;color: #40485B;border-bottom: 1px solid  #cdd1dc;
    border-right: 1px solid  #cdd1dc;" >%s</td>
            </tr>
        </table>';
                $seriesModel = new GoodsCarSeriesModel();
                $brand_data = $seriesModel->getBrandBySeriesId($series_id);
                $book_date = date('Y-m-d H:i:s',$data['book_time']);
                $book_car_style = $brand_data['brand_name'].' '.$brand_data['series_name'];
                $body = sprintf($email_tpl,$customer_name,$book_date,$book_car_style,$mobile);
                $result = cmf_send_email($email_config['to'], $email_config['subject'], $body);
                $this->result(['order_book_id'=>$id],1);
                /*if ($result && empty($result['error'])) {
                    $this->success('发送成功！');
                } else {
                    $this->error('发送失败：' . $result['message']);
                }*/

            }
        }catch(ErrorException $e){
            $this->result('',0,'服务出错,请稍后再试');
        }
    }

    /**
     *
     * 咨询车型底价
     *
     */
    public function ajaxSubmitAskCarPrice(){
        $series_id = I('series_id');
        $style_id = I('style_id');
        $customer_name = I('customer_name');
        $mobile = I('mobile');
        if(empty($series_id)){
            $this->result('',0,'请选择车系');
        }
        if(empty($style_id)){
            $this->result('',0,'请选择车型');
        }
        if(empty($customer_name)){
            $this->result('',0,'请填写姓名');
        }
        if(empty($mobile)){
            $this->result('',0,'请填写电话号码');
        }
        if(strlen($mobile) !== 11|| !preg_match('/^(13[0-9]|15[0-9]|18[0-9])\d{8}$/',$mobile)){
            $this->result('',0,'请输入正确的手机号码格式');
        }

        $wh = [];
        $wh['car_style_id'] = $style_id;
        $wh['series_id'] = $series_id;
        $wh['book_telephone'] = $mobile;
        $wh['dealers_id'] = 0;
        $wh['delete_time'] = 0;
        $orderBookModel = new OrderBookModel();
        $count = $orderBookModel->where($wh)->count();
        if($count>0){
            $this->result('',-1,'您已经咨询');
        }
        $data['name'] = $customer_name;
        $data['area_id'] = 4403; // 区级id 深圳
        $data['sex'] = 0; // 性别id
        $data['car_style_id'] = 0; // 车型id
        $data['book_time'] = time(); // 发布时间
        $data['book_to_time'] = 0; // 预约到店时间
        $data['book_telephone'] = $mobile; // 电话
        $data['series_id'] = $series_id; // 车系
        $data['remark'] = '咨询底价'; // 车系

        $id = $orderBookModel->addOrderBookData($data);
        if($id){
            // 给运维人员发邮件通知
            //$email_config['to'] = 'qingcaozhi@163.com';
            $email_config['to'] = $this->book_car_manger_email;
            $email_config['subject'] = '咨询车型底价';
            $email_tpl = '<table border="0" cellspacing="0" cellpadding="0" width="40%%" align="center">
        <tr>
            <td width="17%%" align="left" height="36" style="font-size: 14px;border-top: 1px solid  #cdd1dc;
border-left: 1px solid  #cdd1dc; padding-left: 5px;">客&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;户:</td>
            <td width="83%%" align="left" height="36" style="font-size: 14px;color: #40485B;border-top: 1px solid  #cdd1dc;
border-right: 1px solid  #cdd1dc;">%s</td>
        </tr>
        <tr>
            <td colspan="2" align="left" height="36" style="padding-left:30px;font-size: 14px;border-right: 1px solid #cdd1dc;border-left: 1px solid  #cdd1dc;color:#40485B;">于 %s 咨询车型底价！</td>
        </tr>
        <tr>
            <td width="17%%" style="font-size: 14px;
border-left: 1px solid  #cdd1dc; padding-left: 5px;">咨询车型:</td>
            <td width="83%%" align="left" height="36" style="font-size: 14px; color: #40485B;
border-right: 1px solid  #cdd1dc;" >%s</td>
        </tr>
        <tr>
            <td width="17%%" style="font-size: 14px;border-bottom: 1px solid  #cdd1dc;
border-left: 1px solid  #cdd1dc; padding-left: 5px;">联系电话:</td>
            <td width="83%%" align="left" height="36" style="font-size: 14px;color: #40485B;border-bottom: 1px solid  #cdd1dc;
border-right: 1px solid  #cdd1dc;" >%s</td>
        </tr>
    </table>';
            $seriesModel = new GoodsCarSeriesModel();
            $brand_data = $seriesModel->getBrandBySeriesId($series_id);
            $book_date = date('Y-m-d H:i:s',$data['book_time']);
            $book_car_style = $brand_data['brand_name'].' '.$brand_data['series_name'];
            $body = sprintf($email_tpl,$customer_name,$book_date,$book_car_style,$mobile);
            $result = cmf_send_email($email_config['to'], $email_config['subject'], $body);
            $this->result(['order_book_id'=>$id],1);
            /*if ($result && empty($result['error'])) {
                $this->success('发送成功！');
            } else {
                $this->error('发送失败：' . $result['message']);
            }*/
        }else{
            $this->result('',0,'服务出错,请稍后再试');
        }
    }

    public function demo(){
        return $this->fetch();
    }

    public function test(){

        $result =   cmf_send_email('qingcaozhi2018@sina.com','测试邮件', '这是一份测试邮件');

        dump($result);

        return $this->fetch();

    }

    public function p8ConfigData(){
        $wey_style =[
            [
                'name'=>'P8&nbsp;尊贵版',
                'item1'=>[
                    'key'=>'价格',
                    'val'=>[
                        [
                            'k'=>'官方指导价',
                            'v'=>'292,800RMB',
                            's'=>'1'
                        ],
                        [
                            'k'=>'补贴后全国统一价',
                            'v'=>' 259,800RMB',
                            's'=>'1'
                        ]
                    ]
                ],
                'item2'=>[
                    'key'=>'基本参数',
                    'val'=>[
                        [
                            'k'=>'长×宽×高（mm）',
                            'v'=>'4760×1931×1655',
                            's'=>'1'
                        ],
                        [
                            'k'=>'轴距（mm）',
                            'v'=>'2950',
                            's'=>'1'
                        ],
                        [
                            'k'=>'最小离地间隙（mm）',
                            'v'=>'180',
                            's'=>'1'
                        ],
                        [
                            'k'=>'接近角(度)',
                            'v'=>'20',
                            's'=>'1'
                        ],
                        [
                            'k'=>'离去角(度)',
                            'v'=>'25',
                            's'=>'1'
                        ],
                        [
                            'k'=>'油箱容积(L)',
                            'v'=>'45',
                            's'=>'1'
                        ]

                    ]
                ],
                'item3'=>[
                    'key'=>'发动机',
                    'val'=>[
                        [
                            'k'=>'发动机类型',
                            'v'=>'汽油',
                            's'=>'1'
                        ],
                        [
                            'k'=>'发动机型号',
                            'v'=>'4C20A',
                            's'=>'1'
                        ],
                        [
                            'k'=>'发动机峰值功率/转速(kW/rpm)',
                            'v'=>'172/5500',
                            's'=>'1'
                        ],
                        [
                            'k'=>'发动机峰值扭矩/转速(N.m/rpm)',
                            'v'=>'360/2200-4000',
                            's'=>'1'
                        ],
                    ]
                ],
                'item4'=>[
                    'key'=>'电动机及电池',
                    'val'=>[
                        [
                            'k'=>'驱动电机类型',
                            'v'=>'永磁同步电机',
                            's'=>'1'
                        ],
                        [
                            'k'=>'BSG电机最大功率(kW)',
                            'v'=>' 15',
                            's'=>'1'
                        ],
                        [
                            'k'=>'BSG电机最大扭矩(N·m)',
                            'v'=>'50',
                            's'=>'1'
                        ],
                        [
                            'k'=>'驱动电机最大功率(kW)',
                            'v'=>'85',
                            's'=>'1'
                        ],
                        [
                            'k'=>'驱动电机最大扭矩(N·m)',
                            'v'=>' 360/2200-4000',
                            's'=>'1'
                        ],
                        [
                            'k'=>'动力电池类型',
                            'v'=>'三元锂离子电池',
                            's'=>'1'
                        ],
                        [
                            'k'=>'动力电池容量(kWh)',
                            'v'=>'12.96',
                            's'=>'1'
                        ],
                        [
                            'k'=>'0-100%充电时间(h)',
                            'v'=>'4',
                            's'=>'1'
                        ],
                    ]
                ],
                'item5'=>[
                    'key'=>'综合性能',
                    'val'=>[
                        [
                            'k'=>'整车综合最大功率(kW)',
                            'v'=>'250',
                            's'=>'1'
                        ],
                        [
                            'k'=>'整车综合最大扭矩(N·m)',
                            'v'=>'524',
                            's'=>'1'
                        ],
                        [
                            'k'=>'0-100km/h加速时间(s)',
                            'v'=>'6.5',
                            's'=>'1'
                        ],
                        [
                            'k'=>'综合工况油耗(L/100km)',
                            'v'=>'2.3',
                            's'=>'1'
                        ],
                        [
                            'k'=>'最高车速(km/h)',
                            'v'=>'230',
                            's'=>'1'
                        ],
                    ]
                ],
                'item6'=>[
                    'key'=>'底盘操控',
                    'val'=>[
                        [
                            'k'=>'变速器',
                            'v'=>'6速湿式双离合变速器',
                            's'=>'1'
                        ],
                        [
                            'k'=>'悬挂系统',
                            'v'=>'麦弗逊式独立前悬挂/多连杆式独立后悬挂',
                            's'=>'1'
                        ],
                        [
                            'k'=>'驱动型式',
                            'v'=>'智能四驱',
                            's'=>'1'
                        ],
                        [
                            'k'=>'制动型式',
                            'v'=>'四轮通风盘式制动',
                            's'=>'1'
                        ],
                        [
                            'k'=>'转向系统型式',
                            'v'=>'电动助力转向',
                            's'=>'1'
                        ],
                        [
                            'k'=>'SPORT模式',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'EV模式',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'AUTO模式',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'SAVE模式',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'AWD模式',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'雪地模式',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'沙地模式',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'泥地模式',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'235/55 R20(米其林)',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'255/50 R20(马牌)',
                            'v'=>'0',
                            's'=>'2'
                        ],
                        [
                            'k'=>'255/45 R21(佳通)',
                            'v'=>'0',
                            's'=>'2'
                        ],
                    ]
                ],
                'item7'=>[
                    'key'=>'安全装备',
                    'val'=>[
                        [
                            'k'=>'ACC自适应巡航(0-150km/h区间开启)',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'FCW前碰撞预警',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'AEB自动刹车系统',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'LKA车道保持',
                            'v'=>'0',
                            's'=>'2'
                        ],
                        [
                            'k'=>'LDW车道偏离预警',
                            'v'=>'0',
                            's'=>'2'
                        ],
                        [
                            'k'=>'LCA并线辅助',
                            'v'=>'0',
                            's'=>'2'
                        ],
                        [
                            'k'=>'BSD盲点监测系统',
                            'v'=>'0',
                            's'=>'2'
                        ],
                        [
                            'k'=>'ESP车身稳定控制系统',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'TCS牵引力控制系统',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'ABS制动防抱死系统',
                            'v'=>'2',
                            's'=>'2'
                        ],[
                            'k'=>'BA智能刹车辅助系统',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'EBD电子制动力分配系统',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'BOS制动优先系统',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'ESS紧急制动警示系统',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'HHC上坡辅助系统',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'HDC陡坡缓降系统',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'驾驶员疲劳提醒',
                            'v'=>'0',
                            's'=>'2'
                        ],
                        [
                            'k'=>'DOW开门预警',
                            'v'=>'0',
                            's'=>'2'
                        ],
                        [
                            'k'=>'CTA倒车侧向警告',
                            'v'=>'0',
                            's'=>'2'
                        ],
                        [
                            'k'=>'半自动泊车',
                            'v'=>'0',
                            's'=>'2'
                        ],
                        [
                            'k'=>'360度全景监视',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'EPB电子驻车系统',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'AUTO HOLD自动驻车系统',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'前/后测距雷达',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'RMI防侧翻',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'TPMS智能胎压监测系统',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'前排双安全气囊',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'前后一体式侧气帘',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'前排侧气囊',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'纯电动行驶声音提示',
                            'v'=>'2',
                            's'=>'2'
                        ],[
                            'k'=>'前/后排预紧式限力安全带',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'儿童安全锁',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'儿童座椅固定装置(LATCH)',
                            'v'=>'2',
                            's'=>'2'
                        ],
                    ]
                ],
                'item8'=>[
                    'key'=>'外观配置',
                    'val'=>[
                        [
                            'k'=>'智能全景天窗',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'矩阵式LED大灯(带ALS+跟随回家)',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'LED前雾灯(带转向自动照明)',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'全LED后组合灯',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'四门把手照明灯',
                            'v'=>'0',
                            's'=>'2'
                        ],
                        [
                            'k'=>'自动大灯+自动雨刷',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'前排静音玻璃',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'后排隐私玻璃',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'20英寸双色刃型铝合金轮毂',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'21英寸多辐银色铝合金轮毂',
                            'v'=>'2',
                            's'=>'2'
                        ],[
                            'k'=>'21英寸多辐黑色铝合金轮毂',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'哑光银外观套件',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'高亮黑外观套件',
                            'v'=>'2',
                            's'=>'2'
                        ],
                    ]
                ],
                'item9'=>[
                    'key'=>'内饰配置',
                    'val'=>[
                        [
                            'k'=>'黑色内饰',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'黑棕内饰',
                            'v'=>'1',
                            's'=>'2'
                        ],
                        [
                            'k'=>'黑红内饰',
                            'v'=>'0',
                            's'=>'2'
                        ],
                        [
                            'k'=>'高亮黑内饰板',
                            'v'=>'1',
                            's'=>'2'
                        ],
                        [
                            'k'=>'科技纹内饰板',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'皮质座椅',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'真皮座椅',
                            'v'=>'0',
                            's'=>'2'
                        ],
                        [
                            'k'=>'前排座椅加热',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'前排座椅通风+按摩功能',
                            'v'=>'0',
                            's'=>'2'
                        ],
                        [
                            'k'=>'主驾驶座椅8向电动调节(带座椅记忆及迎宾)',
                            'v'=>'0',
                            's'=>'2'
                        ],[
                            'k'=>'主驾驶座椅6向电动调节',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'副驾驶座椅4向电动调节',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'运动真皮多功能方向盘(带换挡拨片)',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'PM2.5空调滤芯',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'空气净化系统',
                            'v'=>'0',
                            's'=>'2'
                        ],
                        [
                            'k'=>'LED动感氛围灯(三色可调)',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'LED顶灯/阅读灯',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'车外温度显示',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'冷光迎宾门槛',
                            'v'=>'0',
                            's'=>'2'
                        ],
                        [
                            'k'=>'后排高度可调节头枕',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'豪华脚垫',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'金属装饰踏板及脚歇',
                            'v'=>'0',
                            's'=>'2'
                        ],
                    ]
                ],
                'item10'=>[
                    'key'=>'科技便利配置',
                    'val'=>[
                        [
                            'k'=>'WEY智享互联',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'高清流媒体广角内后视镜',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'12.3英寸全彩高清数字虚拟组合仪表',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'9英寸TFT彩色液晶显示屏(带行车锁屏功能)',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'GPS智能导航系统',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'智能语音识别',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'高级音响系统(9扬声器，带独立功放)',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'随速音量调节',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'感应式电动后背门(带位置记忆及防夹)',
                            'v'=>'0',
                            's'=>'2'
                        ],
                        [
                            'k'=>'电动后背门(带位置记忆及防夹)',
                            'v'=>'0',
                            's'=>'2'
                        ],[
                            'k'=>'一键启动+无钥匙进入',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'双温区自动空调系统',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'AQS空气质量自动控制系统',
                            'v'=>'0',
                            's'=>'2'
                        ],
                        [
                            'k'=>'四门车窗一键升降(带防夹)',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'电动折叠外后视镜(带除霜)',
                            'v'=>'0',
                            's'=>'2'
                        ],
                        [
                            'k'=>'外后视镜倒车记忆辅助',
                            'v'=>'0',
                            's'=>'2'
                        ],
                        [
                            'k'=>'智能车门防误锁',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'车载充电机',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'充电桩',
                            'v'=>'2',
                            's'=>'2'
                        ],
                    ]
                ],
            ],
            [
                'name'=>'P8&nbsp;尊享型',
                'item1'=>[
                    'key'=>'价格',
                    'val'=>[
                        [
                            'k'=>'官方指导价',
                            'v'=>'302,800RMB',
                            's'=>'1'
                        ],
                        [
                            'k'=>'补贴后全国统一价',
                            'v'=>' 269,800RMB',
                            's'=>'1'
                        ]
                    ]
                ],
                'item2'=>[
                    'key'=>'基本参数',
                    'val'=>[
                        [
                            'k'=>'长×宽×高（mm）',
                            'v'=>'4760×1931×1655',
                            's'=>'1'
                        ],
                        [
                            'k'=>'轴距（mm）',
                            'v'=>'2950',
                            's'=>'1'
                        ],
                        [
                            'k'=>'最小离地间隙（mm）',
                            'v'=>'180',
                            's'=>'1'
                        ],
                        [
                            'k'=>'接近角(度)',
                            'v'=>'20',
                            's'=>'1'
                        ],
                        [
                            'k'=>'离去角(度)',
                            'v'=>'25',
                            's'=>'1'
                        ],
                        [
                            'k'=>'油箱容积(L)',
                            'v'=>'45',
                            's'=>'1'
                        ]

                    ]
                ],
                'item3'=>[
                    'key'=>'发动机',
                    'val'=>[
                        [
                            'k'=>'发动机类型',
                            'v'=>'汽油',
                            's'=>'1'
                        ],
                        [
                            'k'=>'发动机型号',
                            'v'=>'4C20A',
                            's'=>'1'
                        ],
                        [
                            'k'=>'发动机峰值功率/转速(kW/rpm)',
                            'v'=>'172/5500',
                            's'=>'1'
                        ],
                        [
                            'k'=>'发动机峰值扭矩/转速(N.m/rpm)',
                            'v'=>'360/2200-4000',
                            's'=>'1'
                        ],
                    ]
                ],
                'item4'=>[
                    'key'=>'电动机及电池',
                    'val'=>[
                        [
                            'k'=>'驱动电机类型',
                            'v'=>'永磁同步电机',
                            's'=>'1'
                        ],
                        [
                            'k'=>'BSG电机最大功率(kW)',
                            'v'=>' 15',
                            's'=>'1'
                        ],
                        [
                            'k'=>'BSG电机最大扭矩(N·m)',
                            'v'=>'50',
                            's'=>'1'
                        ],
                        [
                            'k'=>'驱动电机最大功率(kW)',
                            'v'=>'85',
                            's'=>'1'
                        ],
                        [
                            'k'=>'驱动电机最大扭矩(N·m)',
                            'v'=>' 360/2200-4000',
                            's'=>'1'
                        ],
                        [
                            'k'=>'动力电池类型',
                            'v'=>'三元锂离子电池',
                            's'=>'1'
                        ],
                        [
                            'k'=>'动力电池容量(kWh)',
                            'v'=>'12.96',
                            's'=>'1'
                        ],
                        [
                            'k'=>'0-100%充电时间(h)',
                            'v'=>'4',
                            's'=>'1'
                        ],
                    ]
                ],
                'item5'=>[
                    'key'=>'综合性能',
                    'val'=>[
                        [
                            'k'=>'整车综合最大功率(kW)',
                            'v'=>'250',
                            's'=>'1'
                        ],
                        [
                            'k'=>'整车综合最大扭矩(N·m)',
                            'v'=>'524',
                            's'=>'1'
                        ],
                        [
                            'k'=>'0-100km/h加速时间(s)',
                            'v'=>'6.5',
                            's'=>'1'
                        ],
                        [
                            'k'=>'综合工况油耗(L/100km)',
                            'v'=>'2.3',
                            's'=>'1'
                        ],
                        [
                            'k'=>'最高车速(km/h)',
                            'v'=>'230',
                            's'=>'1'
                        ],
                    ]
                ],
                'item6'=>[
                    'key'=>'底盘操控',
                    'val'=>[
                        [
                            'k'=>'变速器',
                            'v'=>'6速湿式双离合变速器',
                            's'=>'1'
                        ],
                        [
                            'k'=>'悬挂系统',
                            'v'=>'麦弗逊式独立前悬挂/多连杆式独立后悬挂',
                            's'=>'1'
                        ],
                        [
                            'k'=>'驱动型式',
                            'v'=>'智能四驱',
                            's'=>'1'
                        ],
                        [
                            'k'=>'制动型式',
                            'v'=>'四轮通风盘式制动',
                            's'=>'1'
                        ],
                        [
                            'k'=>'转向系统型式',
                            'v'=>'电动助力转向',
                            's'=>'1'
                        ],
                        [
                            'k'=>'SPORT模式',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'EV模式',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'AUTO模式',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'SAVE模式',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'AWD模式',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'雪地模式',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'沙地模式',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'泥地模式',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'235/55 R20(米其林)',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'255/50 R20(马牌)',
                            'v'=>'0',
                            's'=>'2'
                        ],
                        [
                            'k'=>'255/45 R21(佳通)',
                            'v'=>'0',
                            's'=>'2'
                        ],
                    ]
                ],
                'item7'=>[
                    'key'=>'安全装备',
                    'val'=>[
                        [
                            'k'=>'ACC自适应巡航(0-150km/h区间开启)',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'FCW前碰撞预警',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'AEB自动刹车系统',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'LKA车道保持',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'LDW车道偏离预警',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'LCA并线辅助',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'BSD盲点监测系统',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'ESP车身稳定控制系统',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'TCS牵引力控制系统',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'ABS制动防抱死系统',
                            'v'=>'2',
                            's'=>'2'
                        ],[
                            'k'=>'BA智能刹车辅助系统',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'EBD电子制动力分配系统',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'BOS制动优先系统',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'ESS紧急制动警示系统',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'HHC上坡辅助系统',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'HDC陡坡缓降系统',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'驾驶员疲劳提醒',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'DOW开门预警',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'CTA倒车侧向警告',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'半自动泊车',
                            'v'=>'0',
                            's'=>'2'
                        ],
                        [
                            'k'=>'360度全景监视',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'EPB电子驻车系统',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'AUTO HOLD自动驻车系统',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'前/后测距雷达',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'RMI防侧翻',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'TPMS智能胎压监测系统',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'前排双安全气囊',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'前后一体式侧气帘',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'前排侧气囊',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'纯电动行驶声音提示',
                            'v'=>'2',
                            's'=>'2'
                        ],[
                            'k'=>'前/后排预紧式限力安全带',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'儿童安全锁',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'儿童座椅固定装置(LATCH)',
                            'v'=>'2',
                            's'=>'2'
                        ],
                    ]
                ],
                'item8'=>[
                    'key'=>'外观配置',
                    'val'=>[
                        [
                            'k'=>'智能全景天窗',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'矩阵式LED大灯(带ALS+跟随回家)',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'LED前雾灯(带转向自动照明)',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'全LED后组合灯',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'四门把手照明灯',
                            'v'=>'0',
                            's'=>'2'
                        ],
                        [
                            'k'=>'自动大灯+自动雨刷',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'前排静音玻璃',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'后排隐私玻璃',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'20英寸双色刃型铝合金轮毂',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'21英寸多辐银色铝合金轮毂',
                            'v'=>'0',
                            's'=>'2'
                        ],[
                            'k'=>'21英寸多辐黑色铝合金轮毂',
                            'v'=>'0',
                            's'=>'2'
                        ],
                        [
                            'k'=>'哑光银外观套件',
                            'v'=>'0',
                            's'=>'2'
                        ],
                        [
                            'k'=>'高亮黑外观套件',
                            'v'=>'1',
                            's'=>'2'
                        ],
                    ]
                ],
                'item9'=>[
                    'key'=>'内饰配置',
                    'val'=>[
                        [
                            'k'=>'黑色内饰',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'黑棕内饰',
                            'v'=>'1',
                            's'=>'2'
                        ],
                        [
                            'k'=>'黑红内饰',
                            'v'=>'0',
                            's'=>'2'
                        ],
                        [
                            'k'=>'高亮黑内饰板',
                            'v'=>'1',
                            's'=>'2'
                        ],
                        [
                            'k'=>'科技纹内饰板',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'皮质座椅',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'真皮座椅',
                            'v'=>'0',
                            's'=>'2'
                        ],
                        [
                            'k'=>'前排座椅加热',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'前排座椅通风+按摩功能',
                            'v'=>'0',
                            's'=>'2'
                        ],
                        [
                            'k'=>'主驾驶座椅8向电动调节(带座椅记忆及迎宾)',
                            'v'=>'0',
                            's'=>'2'
                        ],[
                            'k'=>'主驾驶座椅6向电动调节',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'副驾驶座椅4向电动调节',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'运动真皮多功能方向盘(带换挡拨片)',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'PM2.5空调滤芯',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'空气净化系统',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'LED动感氛围灯(三色可调)',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'LED顶灯/阅读灯',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'车外温度显示',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'冷光迎宾门槛',
                            'v'=>'0',
                            's'=>'2'
                        ],
                        [
                            'k'=>'后排高度可调节头枕',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'豪华脚垫',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'金属装饰踏板及脚歇',
                            'v'=>'2',
                            's'=>'2'
                        ],
                    ]
                ],
                'item10'=>[
                    'key'=>'科技便利配置',
                    'val'=>[
                        [
                            'k'=>'WEY智享互联',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'高清流媒体广角内后视镜',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'12.3英寸全彩高清数字虚拟组合仪表',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'9英寸TFT彩色液晶显示屏(带行车锁屏功能)',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'GPS智能导航系统',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'智能语音识别',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'高级音响系统(9扬声器，带独立功放)',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'随速音量调节',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'感应式电动后背门(带位置记忆及防夹)',
                            'v'=>'0',
                            's'=>'2'
                        ],
                        [
                            'k'=>'电动后背门(带位置记忆及防夹)',
                            'v'=>'2',
                            's'=>'2'
                        ],[
                            'k'=>'一键启动+无钥匙进入',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'双温区自动空调系统',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'AQS空气质量自动控制系统',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'四门车窗一键升降(带防夹)',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'电动折叠外后视镜(带除霜)',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'外后视镜倒车记忆辅助',
                            'v'=>'0',
                            's'=>'2'
                        ],
                        [
                            'k'=>'智能车门防误锁',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'车载充电机',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'充电桩',
                            'v'=>'2',
                            's'=>'2'
                        ],
                    ]
                ],
            ],
            [
                'name'=>'P8&nbsp;旗舰型',
                'item1'=>[
                    'key'=>'价格',
                    'val'=>[
                        [
                            'k'=>'官方指导价',
                            'v'=>'312,800RMB',
                            's'=>'1'
                        ],
                        [
                            'k'=>'补贴后全国统一价',
                            'v'=>' 279,800RMB',
                            's'=>'1'
                        ]
                    ]
                ],
                'item2'=>[
                    'key'=>'基本参数',
                    'val'=>[
                        [
                            'k'=>'长×宽×高（mm）',
                            'v'=>'4760×1931×1655',
                            's'=>'1'
                        ],
                        [
                            'k'=>'轴距（mm）',
                            'v'=>'2950',
                            's'=>'1'
                        ],
                        [
                            'k'=>'最小离地间隙（mm）',
                            'v'=>'180',
                            's'=>'1'
                        ],
                        [
                            'k'=>'接近角(度)',
                            'v'=>'20',
                            's'=>'1'
                        ],
                        [
                            'k'=>'离去角(度)',
                            'v'=>'25',
                            's'=>'1'
                        ],
                        [
                            'k'=>'油箱容积(L)',
                            'v'=>'45',
                            's'=>'1'
                        ]

                    ]
                ],
                'item3'=>[
                    'key'=>'发动机',
                    'val'=>[
                        [
                            'k'=>'发动机类型',
                            'v'=>'汽油',
                            's'=>'1'
                        ],
                        [
                            'k'=>'发动机型号',
                            'v'=>'4C20A',
                            's'=>'1'
                        ],
                        [
                            'k'=>'发动机峰值功率/转速(kW/rpm)',
                            'v'=>'172/5500',
                            's'=>'1'
                        ],
                        [
                            'k'=>'发动机峰值扭矩/转速(N.m/rpm)',
                            'v'=>'360/2200-4000',
                            's'=>'1'
                        ],
                    ]
                ],
                'item4'=>[
                    'key'=>'电动机及电池',
                    'val'=>[
                        [
                            'k'=>'驱动电机类型',
                            'v'=>'永磁同步电机',
                            's'=>'1'
                        ],
                        [
                            'k'=>'BSG电机最大功率(kW)',
                            'v'=>' 15',
                            's'=>'1'
                        ],
                        [
                            'k'=>'BSG电机最大扭矩(N·m)',
                            'v'=>'50',
                            's'=>'1'
                        ],
                        [
                            'k'=>'驱动电机最大功率(kW)',
                            'v'=>'85',
                            's'=>'1'
                        ],
                        [
                            'k'=>'驱动电机最大扭矩(N·m)',
                            'v'=>' 360/2200-4000',
                            's'=>'1'
                        ],
                        [
                            'k'=>'动力电池类型',
                            'v'=>'三元锂离子电池',
                            's'=>'1'
                        ],
                        [
                            'k'=>'动力电池容量(kWh)',
                            'v'=>'12.96',
                            's'=>'1'
                        ],
                        [
                            'k'=>'0-100%充电时间(h)',
                            'v'=>'4',
                            's'=>'1'
                        ],
                    ]
                ],
                'item5'=>[
                    'key'=>'综合性能',
                    'val'=>[
                        [
                            'k'=>'整车综合最大功率(kW)',
                            'v'=>'250',
                            's'=>'1'
                        ],
                        [
                            'k'=>'整车综合最大扭矩(N·m)',
                            'v'=>'524',
                            's'=>'1'
                        ],
                        [
                            'k'=>'0-100km/h加速时间(s)',
                            'v'=>'6.5',
                            's'=>'1'
                        ],
                        [
                            'k'=>'综合工况油耗(L/100km)',
                            'v'=>'2.3',
                            's'=>'1'
                        ],
                        [
                            'k'=>'最高车速(km/h)',
                            'v'=>'230',
                            's'=>'1'
                        ],
                    ]
                ],
                'item6'=>[
                    'key'=>'底盘操控',
                    'val'=>[
                        [
                            'k'=>'变速器',
                            'v'=>'6速湿式双离合变速器',
                            's'=>'1'
                        ],
                        [
                            'k'=>'悬挂系统',
                            'v'=>'麦弗逊式独立前悬挂/多连杆式独立后悬挂',
                            's'=>'1'
                        ],
                        [
                            'k'=>'驱动型式',
                            'v'=>'智能四驱',
                            's'=>'1'
                        ],
                        [
                            'k'=>'制动型式',
                            'v'=>'四轮通风盘式制动',
                            's'=>'1'
                        ],
                        [
                            'k'=>'转向系统型式',
                            'v'=>'电动助力转向',
                            's'=>'1'
                        ],
                        [
                            'k'=>'SPORT模式',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'EV模式',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'AUTO模式',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'SAVE模式',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'AWD模式',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'雪地模式',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'沙地模式',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'泥地模式',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'235/55 R20(米其林)',
                            'v'=>'0',
                            's'=>'2'
                        ],
                        [
                            'k'=>'255/50 R20(马牌)',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'255/45 R21(佳通)',
                            'v'=>'1',
                            's'=>'2'
                        ],
                    ]
                ],
                'item7'=>[
                    'key'=>'安全装备',
                    'val'=>[
                        [
                            'k'=>'ACC自适应巡航(0-150km/h区间开启)',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'FCW前碰撞预警',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'AEB自动刹车系统',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'LKA车道保持',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'LDW车道偏离预警',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'LCA并线辅助',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'BSD盲点监测系统',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'ESP车身稳定控制系统',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'TCS牵引力控制系统',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'ABS制动防抱死系统',
                            'v'=>'2',
                            's'=>'2'
                        ],[
                            'k'=>'BA智能刹车辅助系统',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'EBD电子制动力分配系统',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'BOS制动优先系统',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'ESS紧急制动警示系统',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'HHC上坡辅助系统',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'HDC陡坡缓降系统',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'驾驶员疲劳提醒',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'DOW开门预警',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'CTA倒车侧向警告',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'半自动泊车',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'360度全景监视',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'EPB电子驻车系统',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'AUTO HOLD自动驻车系统',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'前/后测距雷达',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'RMI防侧翻',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'TPMS智能胎压监测系统',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'前排双安全气囊',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'前后一体式侧气帘',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'前排侧气囊',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'纯电动行驶声音提示',
                            'v'=>'2',
                            's'=>'2'
                        ],[
                            'k'=>'前/后排预紧式限力安全带',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'儿童安全锁',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'儿童座椅固定装置(LATCH)',
                            'v'=>'2',
                            's'=>'2'
                        ],
                    ]
                ],
                'item8'=>[
                    'key'=>'外观配置',
                    'val'=>[
                        [
                            'k'=>'智能全景天窗',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'矩阵式LED大灯(带ALS+跟随回家)',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'LED前雾灯(带转向自动照明)',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'全LED后组合灯',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'四门把手照明灯',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'自动大灯+自动雨刷',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'前排静音玻璃',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'后排隐私玻璃',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'20英寸双色刃型铝合金轮毂',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'21英寸多辐银色铝合金轮毂',
                            'v'=>'1',
                            's'=>'2'
                        ],[
                            'k'=>'21英寸多辐黑色铝合金轮毂',
                            'v'=>'1',
                            's'=>'2'
                        ],
                        [
                            'k'=>'哑光银外观套件',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'高亮黑外观套件',
                            'v'=>'1',
                            's'=>'2'
                        ],
                    ]
                ],
                'item9'=>[
                    'key'=>'内饰配置',
                    'val'=>[
                        [
                            'k'=>'黑色内饰',
                            'v'=>'1',
                            's'=>'2'
                        ],
                        [
                            'k'=>'黑棕内饰',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'黑红内饰',
                            'v'=>'1',
                            's'=>'2'
                        ],
                        [
                            'k'=>'高亮黑内饰板',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'科技纹内饰板',
                            'v'=>'1',
                            's'=>'2'
                        ],
                        [
                            'k'=>'皮质座椅',
                            'v'=>'0',
                            's'=>'2'
                        ],
                        [
                            'k'=>'真皮座椅',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'前排座椅加热',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'前排座椅通风+按摩功能',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'主驾驶座椅8向电动调节(带座椅记忆及迎宾)',
                            'v'=>'2',
                            's'=>'2'
                        ],[
                            'k'=>'主驾驶座椅6向电动调节',
                            'v'=>'0',
                            's'=>'2'
                        ],
                        [
                            'k'=>'副驾驶座椅4向电动调节',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'运动真皮多功能方向盘(带换挡拨片)',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'PM2.5空调滤芯',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'空气净化系统',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'LED动感氛围灯(三色可调)',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'LED顶灯/阅读灯',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'车外温度显示',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'冷光迎宾门槛',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'后排高度可调节头枕',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'豪华脚垫',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'金属装饰踏板及脚歇',
                            'v'=>'0',
                            's'=>'2'
                        ],
                    ]
                ],
                'item10'=>[
                    'key'=>'科技便利配置',
                    'val'=>[
                        [
                            'k'=>'WEY智享互联',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'高清流媒体广角内后视镜',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'12.3英寸全彩高清数字虚拟组合仪表',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'9英寸TFT彩色液晶显示屏(带行车锁屏功能)',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'GPS智能导航系统',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'智能语音识别',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'高级音响系统(9扬声器，带独立功放)',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'随速音量调节',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'感应式电动后背门(带位置记忆及防夹)',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'电动后背门(带位置记忆及防夹)',
                            'v'=>'0',
                            's'=>'2'
                        ],[
                            'k'=>'一键启动+无钥匙进入',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'双温区自动空调系统',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'AQS空气质量自动控制系统',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'四门车窗一键升降(带防夹)',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'电动折叠外后视镜(带除霜)',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'外后视镜倒车记忆辅助',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'智能车门防误锁',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'车载充电机',
                            'v'=>'2',
                            's'=>'2'
                        ],
                        [
                            'k'=>'充电桩',
                            'v'=>'2',
                            's'=>'2'
                        ],
                    ]
                ],
            ],
        ];
        return $wey_style;
    }

}
